workspace:
  base: /go
  path: src/github.com/Appscrunch/Multy-back

pipeline:
  build:
    image: golang:1.9.2
    commands:
      - make build

  publish:
    image: plugins/docker
    repo: multyio/backend
    tags: 
      - latest
      - 1.0.7
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  ssh:
    image: appleboy/drone-ssh
    host: 88.198.47.112
    username: multy
    secrets: [ ssh_password ]
    script:
      - cd /data2/home/multy/prod/
      - docker-compose -f docker-compose-prod.yml stop 
      - docker-compose -f docker-compose-prod.yml up -d
    when:
      branch: master

  ssh:
    image: appleboy/drone-ssh
    host: 88.198.47.112
    username: multy
    secrets: [ ssh_password ]
    script:
      - cd /data2/home/multy/dev
      - docker-compose -f docker-compose-dev.yml stop 
      - docker-compose -f docker-compose-dev.yml up -d
    when:
      exclude: [ master/* ]
 
  telegram:
    image: appleboy/drone-telegram
    secrets: [ telegram_token, telegram_to ]
    when:
      status: [ success, failure ]
