workspace:
  base: /go
  path: src/github.com/Appscrunch/Multy-back

pipeline:
  build:
    image: golang:1.9.2
    commands:
      - git branch
      - make build

  publish-master:
    image: plugins/docker
    repo: multyio/backend
    tags: 
      - 1.0.8
      - master
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  ssh-master:
    image: appleboy/drone-ssh
    host: 88.198.47.112
    username: multy
    secrets: [ ssh_password ]
    script:
      - cd /data2/home/multy/prod/
      - docker-compose -f docker-compose-prod.yml stop
      - docker pull multyio/backend:master
      - docker-compose -f docker-compose-prod.yml up -d
    when:
      branch: master

  publish-test:
    image: plugins/docker
    repo: multyio/backend-test
    tags: 
      - latest
      - 1.0.9
    secrets: [ docker_username, docker_password ]
    when: 
      branch: ssl

  ssh-test:
    image: appleboy/drone-ssh
    host: 88.198.47.112
    username: multy
    secrets: [ ssh_password ]
    script:
      - cd /data2/home/multy/test
      - docker-compose -f docker-compose-test.yml stop
      - docker pull multyio/backend-test:latest
      - now=$(date +"%m_%d_%Y__%H_%M_%S")
      - cd backend 
      - if [ -d logs ]; then mv logs logs_$now; fi
      - cd ../
      - docker-compose -f docker-compose-test.yml up -d
    when:
      branch: ssl
 
  telegram:
    image: appleboy/drone-telegram
    secrets: [ telegram_token, telegram_to ]
    when:
      status: [ success, failure ]
