env:
  global:
    # encrypted DOCKER_USERNAME and DOCKER_PASSWORD
    - secure: hHy85cIr/uh8yImQYkpWAL1b2VTXkgknuDsinIDt4EZnA7blFWVbTz7fU+10Gm3y3p3XmwG2KSjaKyHWgcFUgkIiNCN1+GJX0JAO78Ni0hV6jpYD1UP8pCXtMFFqk0ympRIRzYTdsfVPWGASTTcrZLQt2zoy4UiiqFw6q9o9yqpTncIpuPQlJZ5Ll6uPreju15khVIaGf8my6OiZxZetoFgdfj+MRQfbLCs6UP7wwShtofTQF+kM49Lwj6AM0JQo+YuTfP1q9wiK0wNYE3+WKdz2bkZGqE2dt175gA6Vc5znaz7zRd2ct7WqxfKYGuggDwx2I89NPLNzXmfMlgPoGR9ybjbvexA4X/3sDQP8ggB6/MHy7H+cr9AF9XBplkEvgD6QnhP3hkcNvowL4Ty1UqCM6wKDbLhO2vTZdKLbfBDbcmCIQ/6DFCTiXZ40ZRARJxRhPsAO7QJJCzas16lVDXxo4EKTY5w5uBPtr3LiknK5zjTIBOvnxewf3rfQDaVsI5LkeUHy0i+O8Oh6o0d05NPLkPkvrDuWR4I+1cs5ZpbJ4HU4qnha+D0Bnk+ix2aa6C8332/7KeiAF+gr/9lOoi5AFSJ6LkRho8se1ijvZqZ/LeZPke0DGyltwL9sOl21qmpXC+/zPXWTOutTkXvv6cgYKbxDBfDR+pnO9vTwdmY=
    - IMAGE=multyio/multy-back

services:
  - docker

before_script:
  - docker info

script:
  - docker build -t "$IMAGE" .

deploy:
  - provider: script
    script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" &&
            docker push "$IMAGE"
    on:
      branch: master
