version: '3.4'
services:
  multy-back:
    image: golang:1.9
    container_name: multy-back
    working_dir: /go/src/Appscrunch/Multy-back
    volumes:
      - ./:/go/src/Appscrunch/Multy-back
    ports:
      - "5580:5580"
      - "5578:5578"
    depends_on:
      - nsq
      - mongodb
    build:
      context: .

  nsqlookup:
    image: nsqio/nsq
    hostname: nsqlookup
    ports:
      - "4160:4160"
      - "4161:4161"
    command: nsqlookupd

  nsq:
    image: nsqio/nsq
    hostname: nsq
    ports:
      - "4150:4150"
      - "4151:4151"
    links:
      - nsqlookup:nsqlookup
    command: nsqd --broadcast-address nsq --lookupd-tcp-address=nsqlookup:4160

  nsqadmin:
    image: nsqio/nsq
    hostname: nsqadmin
    links:
      - nsqlookup:nsqlookup
    ports:
      - "4171:4171"
    command: nsqadmin --lookupd-http-address=nsqlookup:4161

  mongodb:
    container_name: "mongodb"
    image: mongo:3.4
    command: mongod --smallfiles 
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
      # add logpath
    ports:
      - 27017:27017