version: '3.4'
services:
  multy-back:
    image:  multyio/backend:1.0.0
    command: ["make", "all"]
    volumes:
      - ${pwd}/cmd/multy.config:/go/src/github.com/Appscrunch/Multy-back/cmd/multy.config
      - ${pwd}/cmd/rpc.cert:/go/src/Appscrunch/Multy-back/cmd/rpc.cert
    ports:
      - "6678:6678"
      - "6680:6680"
    depends_on:
      - nsq
      - nsqlookup
      - nsqadmin
      - mongodb

  nsqlookup:
    image: nsqio/nsq
    hostname: nsqlookup
    ports:
      - "4160:4160"
      - "4161:4161"
    command: nsqlookupd

  nsq:
    image: nsqio/nsq
    hostname: nsq
    ports:
      - "4150:4150"
      - "4151:4151"
    links:
      - nsqlookup:nsqlookup
    command: nsqd --broadcast-address nsq --lookupd-tcp-address=nsqlookup:4160

  nsqadmin:
    image: nsqio/nsq
    hostname: nsqadmin
    links:
      - nsqlookup:nsqlookup
    ports:
      - "4171:4171"
    command: nsqadmin --lookupd-http-address=nsqlookup:4161

  mongodb:
    container_name: "mongodb"
    image: mongo:3.4
    command: mongod --smallfiles 
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
      # add logpath
    ports:
      - 27017:27017